### ISSUE TITLE
xdm，我遇到bug了

### ISSUE THREAD

**Issue by xiaodaren666** [arcxingye/EatKano#100]
在Firefox选择游戏模式能正常使用，Chromium缺不可以

**Comment by zjkwdy** [comment]
如果你是指每次刷新后都会变成练习模式
不介意的话可以试试[pages版本](https://arcxingye.github.io/EatKano/index.html)（没有排行榜）
星夜貌似没有往xingye.me合并后续的修复版本..

**Comment by xiaodaren666** [comment]
不是...我指的是在Chromium内核的浏览器中点击练习模式没有反应，无法选择游戏模式，而Firefox浏览器可以正常使用

**Comment by kifuan** [comment]
半天也不给具体情况说明和截图，关了
