### ISSUE TITLE
无法使用排行榜功能

### ISSUE THREAD

**Issue by hyb-oyqq** [arcxingye/EatKano#176]
conn.php里的内容都改了，但是没有数据写入到数据库的表里面
看php和mysql日志也没任何尝试写入或访问的记录
php版本5.6和7.4都试了

**Comment by hyb-oyqq** [comment]
按照#39 里面的分析打开F12检查后显示请传递正确的json参数

**Comment by kifuan** [comment]
长时间未补充更多信息，关闭。
