### ISSUE TITLE
有考虑加个封神榜吗

### ISSUE THREAD

**Issue by bilibiliwudian** [arcxingye/EatKano#18]
![image](https://user-images.githubusercontent.com/39687774/150732796-8cd926fb-2839-479e-b199-9122ea7cc44c.png)

**Comment by SakuraKoi** [comment]
草宁还真扔了个issue啊!?

**Comment by bilibiliwudian** [comment]
> 草宁还真扔了个issue啊!?

出现了！作弊幕后煮屎人！

**Comment by SakuraKoi** [comment]
> > 草宁还真扔了个issue啊!?
> 
> 出现了！作弊幕后煮屎人！

宁不也在刷么(恼

**Comment by bilibiliwudian** [comment]
> > > 草宁还真扔了个issue啊!?
> > 
> > 
> > 出现了！作弊幕后煮屎人！
> 
> 宁不也在刷么(恼

恁先整的活(赞赏

**Comment by arcxingye** [comment]
先提高安全性再说吧
现在能直接改的没啥意思

**Comment by zjkwdy** [comment]
那样会全是各路[高技术力神仙]的大会师
