### ISSUE TITLE
请问该项目是否允许修改移植？

### ISSUE THREAD

**Issue by c86-moe** [arcxingye/EatKano#2]
该项目没有注明使用的协议，因此依照通常规定这个项目是属于“保留所有权利”的状态。但README文档中又提及“不需要排行榜把PHP文件都扔掉即可"。
请问该项目是否允许修改代码或发布修改的代码呢？万分感谢。

**Comment by arcxingye** [comment]
随便修改和发布

**Comment by c86-moe** [comment]
十分感谢！
