### ISSUE TITLE
关于反作弊

### ISSUE THREAD

**Issue by zjkwdy** [arcxingye/EatKano#24]
在开局后修改__gs__（分数）变量(未被加密)
就可以随便上传记录。。各种加密措施直接形同虚设。。

**Comment by arcxingye** [comment]
这个修起来比较麻烦，等有缘人来pr吧
我过年还往网吧跑去改代码有点蚌埠住了

**Comment by arcxingye** [comment]
#36

**Comment by zjkwdy** [comment]
不用这么复杂，倒查请求发出的位置，然后在前面打断点，在开一局提交之前就会断在前面。然后手动修改各种变量即可。另外各种函数也是公开的，window.encrypt等等依旧可以随意重写。

**Comment by arcxingye** [comment]
> 其实还是没有修复，依然可以通过 `window._game*` 来访问这些变量

@kifuan

**Comment by zjkwdy** [comment]
这么晚了还不睡啊

**Comment by kifuan** [comment]
我如果用反调试他还是能反了我的反调试(摊手)
就算能防住修改变量，那些用脚本的怎么防

**Comment by kifuan** [comment]
> > 其实还是没有修复，依然可以通过 `window._game*` 来访问这些变量
> 
> @kifuan

我如果用反调试他还是能反了我的反调试(摊手)
就算能防住修改变量，那些用脚本的怎么防

**Comment by wdsjimin** [comment]
我说啊，你们自己上线连公钥都不改一下的吗？`_0x2f1b('52')`和`window._0x24ae[82]`都能看到你们的公钥。这跟开源代码中给出来的别无二致。

**Comment by kasuganosoras** [comment]
兄啊，GitHub 留言的修改记录是可以看到的

**Comment by arcxingye** [comment]
> 希望你们能在邮箱看到通知，这个我先修改了。免得被人利用

没事啊，最近测试用的，正好你赶上了我们复制粘贴

**Comment by zjkwdy** [comment]
撅了，有人重写`Math.random`使目标一直生成在第一格
