### ISSUE TITLE
xingye.me国内大面积无法访问

### ISSUE THREAD

**Issue by george-jiang-wow** [arcxingye/EatKano#242]
2022-9-14

**Comment by george-jiang-wow** [comment]
另：作者可以把羊了个羊搬上来吗🫰谢谢了

**Comment by arcxingye** [comment]
1.站长之家测了下并没红，顶多就卡点
2.网传apk里有源码，随便下个就行，我不敢搬

**Comment by george-jiang-wow** [comment]
![ZIYLgz.png](https://www.helloimg.com/images/2022/09/15/ZIYLgz.png)但是我这边测出来是全红 网站无法访问 您能否再排查下？谢谢

**Comment by arcxingye** [comment]
你要是用ITDOG你注意一下，用那个网站测速，单测eatkano的链接，而不是我的首页，我首页东西比较多，会超10s，在这个工具下超10s就是红，而不是无法访问

**Comment by george-jiang-wow** [comment]
感谢您的回复。网站测速的确是好的。但现在我无论访问首页 还是eatkano都会提示ERR_TIMED_OUT，您能否跟进排查下？谢谢了

**Comment by george-jiang-wow** [comment]
您好 我按照您说的方法本地解压APK之后用serve运行，但网站API进行了登录鉴权  请问有没有绕过的方法？谢谢![](https://www.helloimg.com/images/2022/09/15/ZIYiaA.png)
