### ISSUE TITLE
奇怪的I18N识别

### ISSUE THREAD

**Issue by z0z0r4** [arcxingye/EatKano#250]
![image](https://user-images.githubusercontent.com/78744121/194328626-069db0a4-5f1a-468a-95ae-71ae820cfb50.png)

**Comment by z0z0r4** [comment]
![image](https://user-images.githubusercontent.com/78744121/194330840-dff9594d-1534-4e2f-b5a1-ece957186687.png)

**Comment by arcxingye** [comment]
搜狐这个是定位用的，也就是排行榜显示那个地区，稍后会去除。前端i18n识别用的是navigator.language，你可以控制台打一下console.log(navigator.language);看看你浏览器的

**Comment by kifuan** [comment]
你跑新加的这段看看是什么内容。
正则来于MDN的示例：https://developer.mozilla.org/zh-CN/docs/Web/API/Navigator/language

```js
const LANGUAGES = [
    { regex: /^zh\b/, lang: 'zh' },
    { regex: /^ja\b/, lang: 'ja' },
    { regex: /.*/, lang: 'en'}
]
LANGUAGES.find(l => l.regex.test(navigator.language)).lang
```

**Comment by kifuan** [comment]
并且根据这里，`Array.prototype.find` 是按元素顺序找的，不存在一开始就去匹配 `.*` 的问题：https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/find
