### ISSUE TITLE
排行榜页面显示Warning和Notice

### ISSUE THREAD

**Issue by VeryrrDefine** [arcxingye/EatKano#287]
![image](https://github.com/arcxingye/EatKano/assets/123611096/379836e1-eff4-4109-bed9-a939fc4afdb6)
环境：Windows7，nginx1.18.0，mysql-8.0.33
如图所示，访问rank.php会显示
Warning
: mysqli_fetch_row() expects parameter 1 to be mysqli_result, bool given in
E:\myfirstnginxserver\eatkano\rank.php
on line
143

Notice
: Trying to access array offset on value of type null in
E:\myfirstnginxserver\eatkano\rank.php
on line
143
或许和这个sql语句有关系
![image](https://github.com/arcxingye/EatKano/assets/123611096/1dc658cb-cb24-4251-8be6-75e63897c7cb)

**Comment by VeryrrDefine** [comment]
我认为table "kano_rank"是应该存在的
当我执行select count(*) from "kano_rank" WHERE DATE_SUB(CURDATE(), INTERNAL 7 DAY) <=  date(time)
mysql客户端会报错
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that
corresponds to your MySQL server version for the right syntax to use near '"kano
_rank" WHERE DATE_SUB(CURDATE(), INTERNAL 7 DAY) <=  date(time)' at line 1

**Comment by kifuan** [comment]
able "kano_rank"是应该存在的 当我执行select count(*) from "kano_rank" WHERE DATE_SUB(CURDATE(), INTERNAL 7 DAY) <= date(time) mysql客户端会报错 ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"kano _rank" WHERE DATE_SUB(CURDATE(), INTERNAL 7 DAY) <= date(time)' at line 1

这个报错的原因是你用了双引号。。。应该用反引号
