### ISSUE TITLE
建议监听键盘事件

### ISSUE THREAD

**Issue by mcxiaolan** [arcxingye/EatKano#3]
电脑玩起来累惨啦
顺便可以说一下改在什么地方吗？以便到时候自己更新，因为魔改的差不多了（

**Comment by kZime** [comment]
建议支持dfjk，4key下落式音游）

**Comment by arcxingye** [comment]
@ALINGCAT

**Comment by xem8k5** [comment]
> @ALINGCAT

好像可以用js监听按键来模拟鼠标点击，我先去试试看

**Comment by kifuan** [comment]
我在我的魔改版项目里添加上了 貌似可以
我试着恢复到原版 加上那个功能 然后建一个pull request
