### ISSUE TITLE
星夜大佬好

### ISSUE THREAD

**Issue by Deyi233** [arcxingye/EatKano#35]
俺是一个纯纯的门外汉，如果冒犯还请谅解www
在期末考试的时候同学转了吃掉小鹿乃这个游戏给我，然后就上头了，压根没复习。
放了寒假就自己摸索着用大佬的开源随便改了下图和字（即使这样还耗了老长时间），许多朋友见到就希望我发布一个关于魔改这个游戏的教程，如果大佬同意的话我会在开头就附上出处来源。感谢大佬!

**Comment by arcxingye** [comment]
随便的。
还有，不是大佬
