### ISSUE TITLE
 没有找到 1333333 的记录(或被过滤)

### ISSUE THREAD

**Issue by hifi45** [arcxingye/EatKano#39]
这是什么原因造成！我按照要求搭建的网站。

**Comment by arcxingye** [comment]
在最新提交中改了下[sql语句修正](https://github.com/arcxingye/EatKano/commit/bbb0e46b74807c02e04e61d949dafda237c15a00)
使用此更新后仍然提交不了请查看f12 -> Network -> submitResult->Preview
