### ISSUE TITLE
设置按键时会意外开始游戏

### ISSUE THREAD

**Issue by AustinZW** [arcxingye/EatKano#40]
在“游戏设置”页面进行按键设置时，若输入了修改前的按键，且该按键对应开始游戏的键，则会意外开始游戏。

*eg:* 游戏的默认按键为“**DFJK**”，即这局游戏中要按下对应第二列的键“**F**”来开始游戏。当在文本框中输入“**f**”时，游戏会开始。（*第一个人物消失，开始读秒*）

[![issue_eg1](https://s4.ax1x.com/2022/01/25/7HzY0P.md.png)](https://imgtu.com/i/7HzY0P)

在**PC**上使用Microsoft Edge（*版本 97.0.1072.69*）时发现了此问题，**安卓端**使用Microsoft Edge（*版本46.02.4.5147*）测试尚无此问题。

**Comment by kifuan** [comment]
#45
