### ISSUE TITLE
照片可以自定义吗  想把朋友的弄上去

### ISSUE THREAD

**Issue by 9464675** [arcxingye/EatKano#41]

**Comment by arcxingye** [comment]
兄啊，你都会提issues了，还不会fork改图改字嘛?

**Comment by 9464675** [comment]
我不会呀哥哥…你能帮帮我吗？

**Comment by ALINGCAT** [comment]
> 我不会呀哥哥…你能帮帮我吗？

你就算不看源码也稍微看看文件结构吧.. 你打开static看看

**Comment by tianweimiman** [comment]
Clone本地修改好图片以后怎么commit呀😭

**Comment by zjkwdy** [comment]
> Clone本地修改好图片以后怎么commit呀😭

你都会拼commit了，怎么commit还不会百度一下吗

**Comment by Danielissilly** [comment]
音频可以自定义吗 想把朋友的弄上去
