### ISSUE TITLE
有考虑加别的模式吗

### ISSUE THREAD

**Issue by xem8k5** [arcxingye/EatKano#9]
https://www.xem8k5.ml/EatAnuke/Anuke/index
我的魔改

我这里格外魔改出了一个无限模式和一个练习模式，另外你这个模板真不错

**Comment by FeletexGee** [comment]
> https://www.xem8k5.ml/EatAnuke/Anuke/index 我的魔改
> 
> 我这里格外魔改出了一个无限模式和一个练习模式，另外你这个模板真不错

其实你可以把作者的更新加上 特别是键盘支持 不然半夜根本不方便玩（恼

**Comment by LingASDJ** [comment]
Anuke,hjh

**Comment by kifuan** [comment]
#50
