### ISSUE TITLE
鼠标点击的图标是否可以跟点击前后的图片那样进行设置

### ISSUE THREAD

**Issue by wanghaisheng** [arcxingye/EatKano#94]
比如我搞个锤子之类的
@arcxingye

**Comment by ldcivan** [comment]
可以考虑使用json改变指针图标，下面是一个参考：
function pointer(img)
{
img.style.cursor='url(url/of/image),auto';
｝

**Comment by ldcivan** [comment]
可能的改进方法(基于源index.js内既有内容改编，**未验证**)<br>

index.php/html
‘’‘
<input type="button" class="btn btn-secondary btn-lg" onclick="getPointerImage()" value="指针图片设定" style="left: 0">
<input type="file" id="pointer-image" accept="image/*" style="display: none;" onchange="savePointerImage()">
’‘’
<br>
index.js
‘’‘
w.getClickBeforeImage = function() {
        $('#pointer-image').click();
}
w.savePointerImage = function() {
      const img = document.getElementById('pointer-image');
      body.style.cursor='url(url/of/image),auto';
}
’‘’

**Comment by ldcivan** [comment]
上半块代码建议放在index的
```
<div class="container mb-3">
                        <input type="button" class="btn btn-secondary btn-lg" onclick="getClickBeforeImage()" value="点击前图" style="left: 0">
                        <input type="file" id="click-before-image" accept="image/*" style="display: none;" onchange="saveClickBeforeImage()">
                        <input type="button" class="btn btn-secondary btn-lg" onclick="getClickAfterImage()" value="点击后图" style="right: 0">
                        <input type="file" id="click-after-image" accept="image/*" style="display: none;" onchange="saveClickAfterImage()">
                        <input id="sound" type="button" class="btn btn-secondary btn-lg" onclick="changeSoundMode()">
</div>
```
这个div内以便点击前后图片设置和指针设置都在一起；<br><br>
后半块代码就随便扔在index.js尾部就好

**Comment by GLH-K** [comment]
Lenshu.ksjuw:sonfoliak’n&8:&ks

**Comment by snapchat666** [comment]
哈哈哈
